### PR TITLE
dev-fix_install_external

### PR DESCRIPTION
**Pull request by wguanicedew**
dev-fix_install_external

### CODE REVIEW

**Comment by complynx** [comment]
Your code still works awful on Windows machines.

**Comment by wguanicedew** [comment]
Do we need to support windonw?

**Comment by complynx** [comment]
It's my primary environment. Even without that, it may appear in the future, that someone will also participate and will have windows.

**Comment by complynx** [comment]
It is about development environment, not the production one.

**Comment by complynx** [comment]
And actually I don't support one, I'm doing platform independent things

**Comment by DanilaOleynik** [comment]
No, we don’t. Even in long term.

**Comment by complynx** [comment]
It was about development environment, not the working one.

Kind Regards,
Daniel Driezshuk

19.07.2016 19:30, DanilaOleynik пишет:

**Comment by complynx** [comment]
I'm starting to make stubs for each module, so I need to have the proper environment.

**Pull request closed without merging**
