### PR TITLE
Great refactoring of tools

### PR DESCRIPTION
**Pull request by complynx**
Wen, please, test it in your environment.
I made the refactoring, it ought to work, but it may fail where I couldn't test it.

### CODE REVIEW

**Comment by wguanicedew** [comment]
cannot be tested.

[wguan@lxplus059 pilot-2.0]$ /usr/bin/python -m pip install -r /tmp/wguan/pilot-2.0/tools/pip-requires-test --root=./tools/externals/
/usr/bin/python: pip is a package and cannot be directly executed
[wguan@lxplus059 pilot-2.0]$ 

[wguan@lxplus059 pilot-2.0]$ python tools/install_venv.py 
Creating venv...
done.
Installing pip in virtualenv... done.
Installing dependencies with pip (this can take a while)...
You must give at least one requirement to install (see "pip help install")
Requirement already satisfied (use --upgrade to upgrade): unittest2>=1.1.0 in ./.venv/lib/python2.6/site-packages (from -r /tmp/wguan/pilot-2.0/tools/pip-requires-test (line 3))
Requirement already satisfied (use --upgrade to upgrade): pep8>=1.7.0 in ./.venv/lib/python2.6/site-packages (from -r /tmp/wguan/pilot-2.0/tools/pip-requires-test (line 4))
Requirement already satisfied (use --upgrade to upgrade): flake8>=2.5.4 in ./.venv/lib/python2.6/site-packages (from -r /tmp/wguan/pilot-2.0/tools/pip-requires-test (line 5))
Requirement already satisfied (use --upgrade to upgrade): pytest>=2.9.0 in ./.venv/lib/python2.6/site-packages (from -r /tmp/wguan/pilot-2.0/tools/pip-requires-test (line 6))
Requirement already satisfied (use --upgrade to upgrade): requests>=2.10.0 in ./.venv/lib/python2.6/site-packages (from -r /tmp/wguan/pilot-2.0/tools/pip-requires-test (line 7))
Requirement already satisfied (use --upgrade to upgrade): nose>=1.3.7 in ./.venv/lib/python2.6/site-packages (from -r /tmp/wguan/pilot-2.0/tools/pip-requires-test (line 8))
Requirement already satisfied (use --upgrade to upgrade): pep8-naming in ./.venv/lib/python2.6/site-packages (from -r /tmp/wguan/pilot-2.0/tools/pip-requires-test (line 9))
Requirement already satisfied (use --upgrade to upgrade): mccabe in ./.venv/lib/python2.6/site-packages (from -r /tmp/wguan/pilot-2.0/tools/pip-requires-test (line 10))
Requirement already satisfied (use --upgrade to upgrade): flake8-blind-except in ./.venv/lib/python2.6/site-packages (from -r /tmp/wguan/pilot-2.0/tools/pip-requires-test (line 11))
Requirement already satisfied (use --upgrade to upgrade): argparse in ./.venv/lib/python2.6/site-packages (from unittest2>=1.1.0->-r /tmp/wguan/pilot-2.0/tools/pip-requires-test (line 3))
Requirement already satisfied (use --upgrade to upgrade): six>=1.4 in ./.venv/lib/python2.6/site-packages (from unittest2>=1.1.0->-r /tmp/wguan/pilot-2.0/tools/pip-requires-test (line 3))
Downloading/unpacking traceback2 (from unittest2>=1.1.0->-r /tmp/wguan/pilot-2.0/tools/pip-requires-test (line 3))
  Downloading traceback2-1.4.0.tar.gz
  Running setup.py egg_info for package traceback2
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/tmp/wguan/pilot-2.0/.venv/build/traceback2/setup.py", line 5, in <module>
        pbr=True)
      File "/usr/lib64/python2.6/distutils/core.py", line 113, in setup
        _setup_distribution = dist = klass(attrs)
      File "/tmp/wguan/pilot-2.0/.venv/lib/python2.6/site-packages/setuptools/dist.py", line 265, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/tmp/wguan/pilot-2.0/.venv/lib/python2.6/site-packages/setuptools/dist.py", line 289, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/tmp/wguan/pilot-2.0/.venv/lib/python2.6/site-packages/pkg_resources.py", line 618, in resolve
        dist = best[req.key] = env.best_match(req, self, installer)
      File "/tmp/wguan/pilot-2.0/.venv/lib/python2.6/site-packages/pkg_resources.py", line 862, in best_match
        return self.obtain(req, installer) # try and download/install
      File "/tmp/wguan/pilot-2.0/.venv/lib/python2.6/site-packages/pkg_resources.py", line 874, in obtain
        return installer(requirement)
      File "/tmp/wguan/pilot-2.0/.venv/lib/python2.6/site-packages/setuptools/dist.py", line 339, in fetch_build_egg
        return cmd.easy_install(req)
      File "/tmp/wguan/pilot-2.0/.venv/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 623, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/tmp/wguan/pilot-2.0/.venv/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 653, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/tmp/wguan/pilot-2.0/.venv/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 849, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/tmp/wguan/pilot-2.0/.venv/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 1130, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/tmp/wguan/pilot-2.0/.venv/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 1115, in run_setup
        run_setup(setup_script, args)
      File "/tmp/wguan/pilot-2.0/.venv/lib/python2.6/site-packages/setuptools/sandbox.py", line 69, in run_setup
        lambda: execfile(
      File "/tmp/wguan/pilot-2.0/.venv/lib/python2.6/site-packages/setuptools/sandbox.py", line 120, in run
        return func()
      File "/tmp/wguan/pilot-2.0/.venv/lib/python2.6/site-packages/setuptools/sandbox.py", line 71, in <lambda>
        {'**file**':setup_script, '**name**':'**main**'}
      File "setup.py", line 22, in <module>

```
  File "/tmp/wguan/easy_install-K4l7U3/pbr-1.10.0/pbr/util.py", line 264, in cfg_to_args
  File "/tmp/wguan/easy_install-K4l7U3/pbr-1.10.0/pbr/util.py", line 573, in wrap_commands
  File "/tmp/wguan/pilot-2.0/.venv/lib/python2.6/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/tmp/wguan/pilot-2.0/.venv/lib/python2.6/site-packages/flake8/main.py", line 6, in <module>
    import pycodestyle as pep8
ImportError: No module named pycodestyle
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
```

  File "<string>", line 16, in <module>

  File "/tmp/wguan/pilot-2.0/.venv/build/traceback2/setup.py", line 5, in <module>

```
pbr=True)
```

  File "/usr/lib64/python2.6/distutils/core.py", line 113, in setup

```
_setup_distribution = dist = klass(attrs)
```

  File "/tmp/wguan/pilot-2.0/.venv/lib/python2.6/site-packages/setuptools/dist.py", line 265, in **init**

```
self.fetch_build_eggs(attrs.pop('setup_requires'))
```

  File "/tmp/wguan/pilot-2.0/.venv/lib/python2.6/site-packages/setuptools/dist.py", line 289, in fetch_build_eggs

```
parse_requirements(requires), installer=self.fetch_build_egg
```

  File "/tmp/wguan/pilot-2.0/.venv/lib/python2.6/site-packages/pkg_resources.py", line 618, in resolve

```
dist = best[req.key] = env.best_match(req, self, installer)
```

  File "/tmp/wguan/pilot-2.0/.venv/lib/python2.6/site-packages/pkg_resources.py", line 862, in best_match

```
return self.obtain(req, installer) # try and download/install
```

  File "/tmp/wguan/pilot-2.0/.venv/lib/python2.6/site-packages/pkg_resources.py", line 874, in obtain

```
return installer(requirement)
```

  File "/tmp/wguan/pilot-2.0/.venv/lib/python2.6/site-packages/setuptools/dist.py", line 339, in fetch_build_egg

```
return cmd.easy_install(req)
```

  File "/tmp/wguan/pilot-2.0/.venv/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 623, in easy_install

```
return self.install_item(spec, dist.location, tmpdir, deps)
```

  File "/tmp/wguan/pilot-2.0/.venv/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 653, in install_item

```
dists = self.install_eggs(spec, download, tmpdir)
```

  File "/tmp/wguan/pilot-2.0/.venv/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 849, in install_eggs

```
return self.build_and_install(setup_script, setup_base)
```

  File "/tmp/wguan/pilot-2.0/.venv/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 1130, in build_and_install

```
self.run_setup(setup_script, setup_base, args)
```

  File "/tmp/wguan/pilot-2.0/.venv/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 1115, in run_setup

```
run_setup(setup_script, args)
```

  File "/tmp/wguan/pilot-2.0/.venv/lib/python2.6/site-packages/setuptools/sandbox.py", line 69, in run_setup

```
lambda: execfile(
```

  File "/tmp/wguan/pilot-2.0/.venv/lib/python2.6/site-packages/setuptools/sandbox.py", line 120, in run

```
return func()
```

  File "/tmp/wguan/pilot-2.0/.venv/lib/python2.6/site-packages/setuptools/sandbox.py", line 71, in <lambda>

```
{'__file__':setup_script, '__name__':'__main__'}
```

  File "setup.py", line 22, in <module>

  File "/tmp/wguan/easy_install-K4l7U3/pbr-1.10.0/pbr/util.py", line 264, in cfg_to_args

  File "/tmp/wguan/easy_install-K4l7U3/pbr-1.10.0/pbr/util.py", line 573, in wrap_commands

  File "/tmp/wguan/pilot-2.0/.venv/lib/python2.6/site-packages/pkg_resources.py", line 2260, in load

```
entry = __import__(self.module_name, globals(),globals(), ['__name__'])
```

  File "/tmp/wguan/pilot-2.0/.venv/lib/python2.6/site-packages/flake8/main.py", line 6, in <module>

```
import pycodestyle as pep8
```

ImportError: No module named pycodestyle

---

Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/wguan/pilot-2.0/.venv/build/traceback2
Storing complete log in /afs/cern.ch/user/w/wguan/.pip/pip.log
Command ".venv/bin/pip install -r /tmp/wguan/pilot-2.0/tools/pip-requires-test" failed.
None
[wguan@lxplus059 pilot-2.0]$

**Comment by complynx** [comment]
Do I see there pilot 2.6, or what THAT was?

**Comment by complynx** [comment]
Try p2.7:

```
[ddrizhuk@lxplus086 ~]$
[ddrizhuk@lxplus086 ~]$ git clone https://github.com/PanDAWMS/pilot-2.0.git
Initialized empty Git repository in /afs/cern.ch/user/d/ddrizhuk/pilot-2.0/.git/
remote: Counting objects: 156, done.
remote: Compressing objects: 100% (148/148), done.
remote: Total 156 (delta 80), reused 0 (delta 0), pack-reused 3
Receiving objects: 100% (156/156), 47.26 KiB, done.
Resolving deltas: 100% (80/80), done.
[ddrizhuk@lxplus086 ~]$ cd pilot
pilot/     pilot-2.0/
[ddrizhuk@lxplus086 ~]$ cd pilot-2.0/
[ddrizhuk@lxplus086 pilot-2.0]$ git checkout mytest
Branch mytest set up to track remote branch mytest from origin.
Switched to a new branch 'mytest'
[ddrizhuk@lxplus086 pilot-2.0]$ git fetch
[ddrizhuk@lxplus086 pilot-2.0]$ ls
lib  LICENSE.txt  MANIFEST.in  README.md  README.rst  setup.cfg  setup.py  SETUP.rst  tools
[ddrizhuk@lxplus086 pilot-2.0]$ python tools/install_venv.py
Failed to install virtualenv with curl.
Creating venv via curl...
[ddrizhuk@lxplus086 pilot-2.0]$ python tools/install_venv.py
Failed to install virtualenv with curl.
Creating venv via curl...
[ddrizhuk@lxplus086 pilot-2.0]$ python -m pip install virtualenv
Collecting virtualenv
/afs/cern.ch/user/d/ddrizhuk/python-modules/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/afs/cern.ch/user/d/ddrizhuk/python-modules/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading virtualenv-15.0.2-py2.py3-none-any.whl (1.8MB)
    100% |████████████████████████████████| 1.8MB 355kB/s
Installing collected packages: virtualenv
Exception:
Traceback (most recent call last):
  File "/afs/cern.ch/user/d/ddrizhuk/python-modules/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/afs/cern.ch/user/d/ddrizhuk/python-modules/lib/python2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/afs/cern.ch/user/d/ddrizhuk/python-modules/lib/python2.7/site-packages/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/afs/cern.ch/user/d/ddrizhuk/python-modules/lib/python2.7/site-packages/pip/req/req_install.py", line 831, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/afs/cern.ch/user/d/ddrizhuk/python-modules/lib/python2.7/site-packages/pip/req/req_install.py", line 1032, in move_wheel_files
    isolated=self.isolated,
  File "/afs/cern.ch/user/d/ddrizhuk/python-modules/lib/python2.7/site-packages/pip/wheel.py", line 346, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/afs/cern.ch/user/d/ddrizhuk/python-modules/lib/python2.7/site-packages/pip/wheel.py", line 324, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/afs/cern.ch/sw/lcg/external/Python/2.7.3/x86_64-slc6-gcc48-opt/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 30] Read-only file system: '/afs/cern.ch/sw/lcg/external/Python/2.7.3/x86_64-slc6-gcc48-opt/lib/python2.7/site-packages/virtualenv.py'
[ddrizhuk@lxplus086 pilot-2.0]$ python -m pip install virtualenv --user
Collecting virtualenv
  Using cached virtualenv-15.0.2-py2.py3-none-any.whl
Installing collected packages: virtualenv
Successfully installed virtualenv-15.0.2
[ddrizhuk@lxplus086 pilot-2.0]$ python tools/install_venv.py
Creating venv...
done.
Installing pip in virtualenv... done.
Installing dependencies with pip (this can take a while)...
You must give at least one requirement to install (see "pip help install")
Collecting unittest2>=1.1.0 (from -r /afs/cern.ch/user/d/ddrizhuk/pilot-2.0/tools/pip-requires-test (line 3))
/afs/cern.ch/user/d/ddrizhuk/python-modules/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/afs/cern.ch/user/d/ddrizhuk/python-modules/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading unittest2-1.1.0-py2.py3-none-any.whl (96kB)
    100% |████████████████████████████████| 102kB 823kB/s
Collecting pep8>=1.7.0 (from -r /afs/cern.ch/user/d/ddrizhuk/pilot-2.0/tools/pip-requires-test (line 4))
  Downloading pep8-1.7.0-py2.py3-none-any.whl (41kB)
    100% |████████████████████████████████| 51kB 2.8MB/s
Collecting flake8>=2.5.4 (from -r /afs/cern.ch/user/d/ddrizhuk/pilot-2.0/tools/pip-requires-test (line 5))
  Downloading flake8-2.6.2-py2.py3-none-any.whl
Collecting pytest>=2.9.0 (from -r /afs/cern.ch/user/d/ddrizhuk/pilot-2.0/tools/pip-requires-test (line 6))
  Downloading pytest-2.9.2-py2.py3-none-any.whl (162kB)
    100% |████████████████████████████████| 163kB 1.1MB/s
Requirement already satisfied (use --upgrade to upgrade): requests>=2.10.0 in /afs/cern.ch/user/d/ddrizhuk/python-modules/lib/python2.7/site-packages (from -r /afs/cern.ch/user/d/ddrizhuk/pilot-2.0/tools/pip-requires-test (line 7))
Collecting nose>=1.3.7 (from -r /afs/cern.ch/user/d/ddrizhuk/pilot-2.0/tools/pip-requires-test (line 8))
  Downloading nose-1.3.7-py2-none-any.whl (154kB)
    100% |████████████████████████████████| 163kB 1.2MB/s
Collecting pep8-naming (from -r /afs/cern.ch/user/d/ddrizhuk/pilot-2.0/tools/pip-requires-test (line 9))
  Downloading pep8_naming-0.4.1-py2.py3-none-any.whl
Collecting mccabe (from -r /afs/cern.ch/user/d/ddrizhuk/pilot-2.0/tools/pip-requires-test (line 10))
  Downloading mccabe-0.5.0-py2.py3-none-any.whl
Collecting flake8-blind-except (from -r /afs/cern.ch/user/d/ddrizhuk/pilot-2.0/tools/pip-requires-test (line 11))
  Downloading flake8-blind-except-0.1.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): argparse in /afs/cern.ch/user/d/ddrizhuk/python-modules/lib/python2.7/site-packages (from unittest2>=1.1.0->-r /afs/cern.ch/user/d/ddrizhuk/pilot-2.0/tools/pip-requires-test (line 3))
Collecting traceback2 (from unittest2>=1.1.0->-r /afs/cern.ch/user/d/ddrizhuk/pilot-2.0/tools/pip-requires-test (line 3))
  Downloading traceback2-1.4.0-py2.py3-none-any.whl
Collecting six>=1.4 (from unittest2>=1.1.0->-r /afs/cern.ch/user/d/ddrizhuk/pilot-2.0/tools/pip-requires-test (line 3))
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting pycodestyle<2.1,>=2.0 (from flake8>=2.5.4->-r /afs/cern.ch/user/d/ddrizhuk/pilot-2.0/tools/pip-requires-test (line 5))
  Downloading pycodestyle-2.0.0-py2.py3-none-any.whl (42kB)
    100% |████████████████████████████████| 51kB 2.3MB/s
Collecting pyflakes!=1.2.0,!=1.2.1,!=1.2.2,<1.3,>=0.8.1 (from flake8>=2.5.4->-r /afs/cern.ch/user/d/ddrizhuk/pilot-2.0/tools/pip-requires-test (line 5))
  Downloading pyflakes-1.2.3-py2.py3-none-any.whl (209kB)
    100% |████████████████████████████████| 215kB 1.3MB/s
Collecting py>=1.4.29 (from pytest>=2.9.0->-r /afs/cern.ch/user/d/ddrizhuk/pilot-2.0/tools/pip-requires-test (line 6))
  Downloading py-1.4.31-py2.py3-none-any.whl (81kB)
    100% |████████████████████████████████| 92kB 2.5MB/s
Requirement already satisfied (use --upgrade to upgrade): setuptools in /afs/cern.ch/user/d/ddrizhuk/python-modules/lib/python2.7/site-packages (from flake8-blind-except->-r /afs/cern.ch/user/d/ddrizhuk/pilot-2.0/tools/pip-requires-test (line 11))
Collecting linecache2 (from traceback2->unittest2>=1.1.0->-r /afs/cern.ch/user/d/ddrizhuk/pilot-2.0/tools/pip-requires-test (line 3))
  Downloading linecache2-1.0.0-py2.py3-none-any.whl
Building wheels for collected packages: flake8-blind-except
  Running setup.py bdist_wheel for flake8-blind-except ... done
  Stored in directory: /afs/cern.ch/user/d/ddrizhuk/.cache/pip/wheels/13/e0/ec/30c1e770f71fb83dcd50721f138a669feb8c3996a82dc31053
Successfully built flake8-blind-except
Installing collected packages: linecache2, traceback2, six, unittest2, pep8, pycodestyle, pyflakes, mccabe, flake8, py, pytest, nose, pep8-naming, flake8-blind-except
Successfully installed flake8-2.6.2 flake8-blind-except-0.1.1 linecache2-1.0.0 mccabe-0.5.0 nose-1.3.7 pep8-1.7.0 pep8-naming-0.4.1 py-1.4.31 pycodestyle-2.0.0 pyflakes-1.2.3 pytest-2.9.2 six-1.10.0 traceback2-1.4.0 unittest2-1.1.0

 Pilot development environment setup is complete.

 Pilot development uses virtualenv to track and manage Python dependencies
 while in development and testing.

 To activate the Pilot virtualenv for the extent of your current shell session
 you can run:

 $ source .venv/bin/activate

 Or, if you prefer, you can run commands in the virtualenv on a case by case
 basis by running:

 $ tools/with_venv.sh <your command>

 Also, make test will automatically use the virtualenv.

[ddrizhuk@lxplus086 pilot-2.0]$
```

**Comment by complynx** [comment]
Now works fine with cURL also

```
[ddrizhuk@lxplus086 pilot-2.0]$ python tools/install_venv.py
Creating venv via curl... done.
Installing pip into virtualenv... done.
Installing dependencies with pip (this can take a while)...
You must give at least one requirement to install (see "pip help install")
Collecting unittest2>=1.1.0 (from -r /afs/cern.ch/user/d/ddrizhuk/pilot-2.0/tools/pip-requires-test (line 3))
/afs/cern.ch/user/d/ddrizhuk/python-modules/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
...
Installing collected packages: linecache2, traceback2, six, unittest2, pep8, pycodestyle, pyflakes, mccabe, flake8, py, pytest, nose, pep8-naming, flake8-blind-except
Successfully installed flake8-2.6.2 flake8-blind-except-0.1.1 linecache2-1.0.0 mccabe-0.5.0 nose-1.3.7 pep8-1.7.0 pep8-naming-0.4.1 py-1.4.31 pycodestyle-2.0.0 pyflakes-1.2.3 pytest-2.9.2 six-1.10.0 traceback2-1.4.0 unittest2-1.1.0

 Pilot development environment setup is complete.

 Pilot development uses virtualenv to track and manage Python dependencies
 while in development and testing.

 To activate the Pilot virtualenv for the extent of your current shell session
 you can run:

 $ source .venv/bin/activate

 Or, if you prefer, you can run commands in the virtualenv on a case by case
 basis by running:

 $ tools/with_venv.sh <your command>

 Also, make test will automatically use the virtualenv.

[ddrizhuk@lxplus086 pilot-2.0]$
```

**Comment by wguanicedew** [comment]
I fixed a problem in my commit. You can merge to it.
For install_venv.py, if using cvmfs, there is still some problem. I need to fix it.
You have lxplus. You can test it yourself now.
[wguan@lxplus059 pilot-2.0]$ python tools/install_external.py 
/tmp/wguan/pilot-2.0
Configure git
Installing pip via wget
Installing pip via wget
--2016-07-19 17:40:50--  https://bootstrap.pypa.io/get-pip.py
Resolving bootstrap.pypa.io... 151.101.12.175
Connecting to bootstrap.pypa.io|151.101.12.175|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1524722 (1.5M) [text/x-python]
Saving to: `/tmp/wguan/tmpMwPhLE/get-pip.py'

100%[====================================================================================================================================================================================================================================>] 1,524,722   3.40M/s   in 0.4s    

2016-07-19 17:40:51 (3.40 MB/s) - `/tmp/wguan/tmpMwPhLE/get-pip.py' saved [1524722/1524722]

/tmp/wguan/tmpVL3ERG/pip.zip/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
/tmp/wguan/tmpVL3ERG/pip.zip/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
Installing dependencies via pip
/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/python/2.7.4-x86_64-slc6-gcc48/sw/lcg/external/Python/2.7.4/x86_64-slc6-gcc48-opt/bin/python: No module named pip
Command "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/python/2.7.4-x86_64-slc6-gcc48/sw/lcg/external/Python/2.7.4/x86_64-slc6-gcc48-opt/bin/python -m pip install -r /tmp/wguan/pilot-2.0/tools/pip-requires-test --root=./tools/externals/" failed.

[wguan@lxplus059 pilot-2.0]$ python tools/install_venv.py 
Failed to install virtualenv with curl.
Creating venv via curl...

**Comment by complynx** [comment]
See my changes. They work fine for the environment with python 2.7. I also added your fixes, manually, because there is nowhere to merge your changes on.

**Comment by complynx** [comment]
See:

```
[ddrizhuk@lxplus076 pilot-2.0]$ python tools/install_external.py
/afs/cern.ch/user/d/ddrizhuk/pilot-2.0
Configure git
Installing dependencies via pip
/afs/cern.ch/user/d/ddrizhuk/python-modules/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/afs/cern.ch/user/d/ddrizhuk/python-modules/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

Pilot development environment setup is complete.

To enable pilot dev environment by running:

$ source tools/setup_dev.sh

[ddrizhuk@lxplus076 pilot-2.0]$
```

**Pull request merged**
